### ISSUE TITLE
Remove db/schema.rb from repo

### ISSUE THREAD

**Issue by alecho** [UpstateRuby/openworks-status-api#18]
@sbjustin mentioned that he usually doesn't have `schema.rb` checked in to the repo because `rake db:migrate` will generate it anyway. Should we remove it?

**Comment by simplyb** [comment]
No because we don't want to rely on migrations to generate the schema.  Migrations should be used to update a target schema and keep developers up to date but schema.rb is the authoritative representation of the current schema.  New developers can join the project with rake db:schema:load rather than running through potentially thousands of migrations.
